// Generated by psc-bundle 0.7.6.1
var PS = { };
(function(exports) {
  "use strict"
  // module Main
  //exports.encodeURIComponent = encodeURIComponent;
  //exports.random = function(){
    //return Math.random();
  //};
  exports.alert = function(msg){
    return function(){
      window.alert(msg);
      return {};
    };
  };
 
})(PS["Main"] = PS["Main"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Main"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Console = PS["Control.Monad.Eff.Console"];     
  var main = $foreign.alert("hello");
  exports["main"] = main;
  exports["alert"] = $foreign.alert;;
 
})(PS["Main"] = PS["Main"] || {});

PS["Main"].main();
